Return error in the Valid() method.
kubewarden/go-policy-template pull request #10
Opened 2021-09-15 20:04 UTC by jvanz

Updates the Valid() method in the Settings type. Thus, the caller can get a explanation why the settings are not valid and print a proper error message.

2021-09-15 20:11 UTC, jvanz commented
FYI: the docs show the function returning bool and error as well. 
https://docs.kubewarden.io/writing-policies/go/03-policy-settings.html#implementing-settings-validation

2021-09-16 07:24 UTC, flavio requested changes
Overall ok, but needs some small tweaks

2021-09-16 07:24 UTC, flavio commented on settings.go
> +	if valid, _ := settings.Valid(); valid {
The only public API exposed by a policy is `validateSettings`, how that works internally is totally up to the developer.
In this case, given the policy doesn't have any setting, the signature of `Valid()` doesn't return any kind of error.

However, I get what you're trying to achieve here. Given this is a project template, we should show something that doesn't take shortcuts.

Having said that, I'm in favor of updating the signature of the `Valid` function, but this specific line of code should not just sweep the error under the carpet.

Please update the code to handle the error too. The code will use the `RejectSettings` API and give back a message that includes the error that was raised.

2021-09-17 08:43 UTC, flavio requested changes
Some changes are needed to ensure we have something generic

2021-09-17 08:43 UTC, flavio commented on settings.go
> +	if valid {
Again, in this context this would be fine, because `Valid()` always return true. However, to make a good foundation I would do something more idiomatic:

```go
if err != nil {
return kubewarden.RejectSettings(kubewarden.Message(fmt.Sprintf("Provided settings are not valid: %v", err)))
}
if valid {
// what you have done
}
```

2021-09-17 08:43 UTC, flavio commented on settings.go
> +	return kubewarden.RejectSettings(kubewarden.Message(fmt.Sprintf("Provided settings are not valid: %v", err)))
Revert with the original line

2021-09-17 08:43 UTC, flavio commented on settings_test.go
>  	}
Again, something more idiomatic where we have two checks:

* assert `err` is `nil`
* assert `valid` is `true`

2021-09-20 21:35 UTC, jvanz commented on settings_test.go
>  	}
I cannot check if `valid` is `true` or `err` is `nil` because this is the opposite of the logic in the test. But I've added the check for err now. Thus, we get the two checks.

2021-09-22 09:02 UTC, flavio approved these changes
that looks good, thanks!

2021-09-22 09:02 UTC, merged