Install local version of kwctl
kubewarden/go-policy-template pull request #21
Opened 2022-04-17 12:57 UTC by alexander-demichev

## Description

This way we can be sure all plugin developers use the same version and it can help track down issues if any appear.

## Test

To test this pull request, you can run the following commands:

## Additional Information

### Tradeoff

### Potential improvement

2022-04-18 08:05 UTC, ereslibre requested changes
Thank you! This is useful for people running policy-related commands using kwctl, when it's not in their `PATH`.

An observation though: if I am a developer that has created a number of policies, I probably don't want to have `kwctl` duplicated on every policy I am writing or have written.

I think it would be a nice addition to do nothing if a `kwctl` is already found in the `PATH`. So that it just works with your current version if you happen to have it already, or it downloads it into your policy `bin` directory otherwise. I think is a good balance.

Also, just for completeness (will need to be done later), it would be amazing to also update the other template projects, so regardless of the language you choose to write your policy in, this part of the experience is similar. They are: https://github.com/topics/kubewarden-policy-template

2022-04-18 08:05 UTC, ereslibre commented on Makefile
> +KWCTL_VER := v0.2.5
```suggestion
KWCTL_VER := latest
```

So that we don't have to follow up on new releases and/or create some automation to push this dependency here. I think we should respect the `kwctl annotate` contract from this point on, and in general, kwctl usage on the templates.

2022-04-18 12:42 UTC, jvanz approved these changes
After fixing Rafa's comments, LGTM.

2022-04-19 10:15 UTC, viccuad approved these changes
Thanks for the PR! I agree with ereslibre comments, besides that, it looks good.

2022-11-03 09:11 UTC, closed without merging