feat: Update Makefile, consume github-actions@v3.0.0
kubewarden/go-policy-template pull request #39
Opened 2023-03-21 15:47 UTC by viccuad

## Description

Relates to https://github.com/kubewarden/kubewarden-controller/issues/389

## Test

Not tested.

## Additional Information

### Tradeoff

### Potential improvement

2023-03-21 17:28 UTC, jvanz approved these changes

2023-03-22 08:19 UTC, flavio commented
> * a `0.0.1` git tag in this repo

Maybe we should start to have tags on this repository. It would make easier to understand what is going on. I just wonder how this would impact on people who create new repositories based on this template. I doubt the tags would propagate to their repos...

> * none, deactivate check artifacthub

Yes, that's the other fix I would do. Just update the settings of this repo to ignore these failures. I hope/doubt this would be propagated to "forked" repos...

2023-03-22 09:00 UTC, flavio commented on Makefile
> +VERSION := $(shell git describe | cut -c2-)
Shouldn't this be:

```
VERSION ?= $(shell git describe | cut -c2-)
```

2023-03-22 11:53 UTC, viccuad commented on Makefile
> +VERSION := $(shell git describe | cut -c2-)
true, done in https://github.com/kubewarden/go-policy-template/pull/39/commits/bc65b8ad50196dd5d81408bb09cb859c65e31b8b.

2023-03-22 17:06 UTC, jvanz requested changes

2023-03-22 17:06 UTC, jvanz commented on .github/workflows/test.yml
> +    uses: kubewarden/github-actions/.github/workflows/reusable-test-policy-go.yml@v3.0.0
```suggestion
    uses: kubewarden/github-actions/.github/workflows/reusable-test-policy-go.yml@v3.0.4
```

2023-03-22 17:13 UTC, jvanz commented
> Maybe we should start to have tags on this repository. It would make easier to understand what is going on. I just wonder how this would impact on people who create new repositories based on this template. I doubt the tags would propagate to their repos.

Yes, I think is a good idea. Considering the github docs:
```
Creating a repository from a template is similar to forking a repository, but there are important differences:

    A new fork includes the entire commit history of the parent repository, while a repository created from a template starts with a single commit.
```

I think the tags will not affect the users creating the repos from the template. If the "forked" repository will have a single commit, there is no reason to import the tags as well. The only consideration is to how we add branches in the template repository. Because user may import them into their repositories:

```
After you make your repository a template, anyone with access to the repository can generate a new repository with the same directory structure and files as your default branch. They can also choose to include all the other branches in your repository. Branches created from a template have unrelated histories, so you cannot create pull requests or merge between the branches. 
```

https://docs.github.com/en/repositories/creating-and-managing-repositories/creating-a-template-repository
https://docs.github.com/en/repositories/creating-and-managing-repositories/creating-a-repository-from-a-template

2023-03-23 10:32 UTC, viccuad commented
So, as a test,
- Created a `v0.0.1-unreleased` tag in this repo: https://github.com/kubewarden/go-policy-template/tree/v0.0.1-unreleased
- Created a fork from the template: https://github.com/viccuad/my-go-template-fork

My fork doesn't get the tag by default, i need to `git fetch && git push -t`. We could add a check to the Makefile: "no tags detected, please make your first or do `git fetch && git push -t`".

2023-03-23 13:31 UTC, flavio commented
Good! let's get this PR merged and then we can start tagging this repo as well

2023-03-24 17:13 UTC, viccuad commented
Merging, leaving the tag in the repo.

2023-03-24 17:13 UTC, merged